import { OccurrenceFieldsFragment } from '../../../../generated/graphql';

export default [
  {
    id: 'T2NjdXJyZW5jZU5vZGU6NzY=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
      { id: 'en', name: 'English', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-14T09:00:00+00:00',
    endTime: '2020-07-14T10:00:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6Nzc=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 30,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-15T09:00:00+00:00',
    endTime: '2020-07-15T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6Nzg=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
      { id: 'en', name: 'English', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-16T09:00:00+00:00',
    endTime: '2020-07-16T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6Nzk=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-20T09:00:00+00:00',
    endTime: '2020-07-20T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODA=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 10,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-21T09:00:00+00:00',
    endTime: '2020-07-21T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODE=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-22T09:00:00+00:00',
    endTime: '2020-07-22T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODI=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-23T09:00:00+00:00',
    endTime: '2020-07-23T11:00:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODM=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-27T09:00:00+00:00',
    endTime: '2020-07-27T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODQ=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 10,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
      { id: 'en', name: 'English', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-28T09:00:00+00:00',
    endTime: '2020-07-28T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODU=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 15,
    autoAcceptance: true,
    languages: [
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
      { id: 'en', name: 'English', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-29T09:00:00+00:00',
    endTime: '2020-07-29T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODY=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'en', name: 'English', __typename: 'LanguageType' },
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-30T09:30:00+00:00',
    endTime: '2020-07-30T10:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
  {
    id: 'T2NjdXJyZW5jZU5vZGU6ODc=',
    pEvent: {
      id: 'UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjcw',
      __typename: 'PalvelutarjotinEventNode',
    },
    amountOfSeats: 30,
    seatsTaken: 0,
    minGroupSize: 10,
    maxGroupSize: 20,
    autoAcceptance: true,
    languages: [
      { id: 'fi', name: 'Finnish', __typename: 'LanguageType' },
      { id: 'en', name: 'English', __typename: 'LanguageType' },
    ],
    startTime: '2020-07-31T09:00:00+00:00',
    endTime: '2020-07-31T09:30:00+00:00',
    placeId: '',
    __typename: 'OccurrenceNode',
  },
] as OccurrenceFieldsFragment[];
