include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 3000

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_ENVIRONMENT: 'review'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_API_BASE_URL: 'https://palvelutarjotin-api.test.kuva.hel.ninja/graphql'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_CAPTCHA_KEY: '$GL_QA_CAPTCHA_KEY'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_ENVIRONMENT: 'staging'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_API_BASE_URL: 'https://palvelutarjotin-api.test.kuva.hel.ninja/graphql'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_CAPTCHA_KEY: '$GL_QA_CAPTCHA_KEY'
  only:
    refs:
      - master

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_ENVIRONMENT: 'production'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_API_BASE_URL: 'https://palvelutarjotin-api.prod.kuva.hel.ninja/graphql'
    DOCKER_BUILD_ARG_NEXT_PUBLIC_CAPTCHA_KEY: '$GL_PRODUCTION_CAPTCHA_KEY'
  only:
    refs:
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0
  only:
    refs:
      - external_pull_requests

staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    POSTGRES_ENABLED: 0
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    POSTGRES_ENABLED: 0
  only:
    refs:
      - /^release-.*$/
