services:
  app:
    container_name: palvelutarjotin-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    environment:
      - WATCHPACK_POLLING=${WATCHPACK_POLLING:-true}
    volumes:
      # Share local directory to enable development with hot reloading
      - .:/app
      # Prevent sharing the following directories between host and container
      # to avoid ownership and/or platform issues:
      - /app/node_modules
      - /app/.next
    ports:
      - '${PORT}:${PORT}'
